### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by leomaurodesenv** [brazanation/php-states#2]
Primeiro, parabéns pelo trabalho. Algo teoricamente simples, porém muito necessário e útil.

**1)** Sugiro a inclusão de mais informações, tais como: latitude e longitude central, capitais, informações demográficas, google maps.. aparenta ser algo "exagerado", mas são compatíveis com sistemas SIG (Sistemas de Informação Geoespaciais).

**2)** A idéia do FULL_NAME para os estados é complicado, tente introduzir uma jogada de nome com hífen, maiúsculo, minúsculo => antes de "ativar" você pode pré-processar a informação transformando-a na desejada ou retornando o erro.

**3)** Dê uma olhada em meus trabalhos tbm! (Heheh) Sugira novas modificações, façam testes! Qualquer coisa estou a disposição. [leomaurodesenv](https://github.com/leomaurodesenv)

**Comment by tonicospinelli** [comment]
@leomaurodesenv Primeiramente, obrigado pelo feedback.

Esse projeto nasceu a partir do NFePHP e pode crescer ainda mais, o intuito inicial era fornecer os dados mais básicos de uma unidade federativa como nome, sigla e código ibge.

**1)** Eu não sei se caberia dentro deste projeto tantas informações deste tipo, talvez latitude e longitude. Vincular Google Maps aqui é um pouco complicado, deveria estar em outro lugar. Pode elencar o que realmente é relevante para um SIG?

**2)** O FULL_NAME inicialmente, não tinha pretenção alguma com ele, apenas exibir o nome completo do estado como escrevemos normalmente.

**3)** Dei uma olhada no seu trabalho, imagino que o que tenha feito foi para aprimorar os estudos, devido ao pouco tempo dos repos e foi um ótimo começo! Para que evolua ainda mais, sugiro que leia sobre as [PSRs](http://www.php-fig.org/), [composer](https://getcomposer.org/) e [PHP The Right Way](http://www.phptherightway.com/). Qualquer dúvida só gritar :smile:

**Comment by leomaurodesenv** [comment]
Ae @tonicospinelli,

**1)** SIG são sistemas que trabalham com informações espaciais do mais diversos tipos: exemplo, Google Maps (a partir de um endereço apresenta um mapa[informações espaciais]); Dados demográficos do IBGE é uma espécie de SIG. No geral, é bem abrangente as informações e tipos de aplicações e as ferramentas disponíveis para isso estão escassas (via web, principalmente php).  [Artigo sobre um SIG - Embrapa](https://www.embrapa.br/monitoramento-por-satelite/busca-de-publicacoes/-/publicacao/859274/plataforma-web-para-sistemas-de-informacao-geoespacial-sig-aplicacoes-no-projeto-geodegrade)

**3)** Obrigado! Estou tentando atualizar meus trabalhos mais recentes para as PSRs, apenas o [FPHP_Loader](https://github.com/leomaurodesenv/FPHP_Loader) e o [FPHP_Fields](https://github.com/leomaurodesenv/FPHP_Fields) estão dentro de alguns padrões.

Tudo de bom!

**Comment by igorwanbarros** [comment]
@tonicospinelli muito boa sua ideia, simples e objetiva!
Meu amigo, dei uma olhada nas classes e vi que apenas o acre esta funcional então gostaria de saber se há intenção de implementar as demais classes e de adicionar mais funcionalidades, como por exemplo converter os dados de um determinado estado para json ou outros tipos (sei lá, apenas uma ideia)...
Caso positivo estarei a disposição para ajudar na implementação!

**Comment by tonicospinelli** [comment]
@igorwanbarros já é possível usar as demais classes
@leomaurodesenv vou fechar essa issue por entender que a sugestão não cabe a este projeto, talvez valha estendê-lo com outro repo
