### ISSUE TITLE
bug  parent::__construct quando não tem extends

### ISSUE THREAD

**Issue by ppKrauss** [brazanation/php-states#5]
Aparentemente apenas o [Acre](https://github.com/brazanation/php-states/blob/master/src/Acre.php) tem `extends State` , precisaria incluir o *extends*  em todas as demais classes. Exemplo corrigir `class Amapa {...}` para `class Amapa extends State {...}`

**Comment by tonicospinelli** [comment]
done! PR #7 solve it
